services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: e-market-api:latest
    env_file:
      - .env.production
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: e-market-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # mongo-express:
  #   image: mongo-express
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongo
  #   restart: unless-stopped

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: unless-stopped


volumes:
  mongo-data:
    name: e-market-mongo-data
